### ISSUE TITLE
May I ask whether it can only perform dataset testing on DOTA servers?

### ISSUE THREAD

**Issue by lnq325805524** [hehaodong530/DOTA-C#1]

**Comment by hehaodong530** [comment]
Yes, dataset testing can only be conducted on the DOTA-v1.0 Server.

**Comment by lnq325805524** [comment]
Thank you for your response. For the results of different corruptions, do I have to upload them one by one to the DOTA server for testing?

**Comment by hehaodong530** [comment]
> Thank you for your response. For the results of different corruptions, do I have to upload them one by one to the DOTA server for testing?

Yes, uploading them one by one to the DOTA server for testing is currently only supported, but we will provide a more efficient method soon.

**Comment by lnq325805524** [comment]
Got it， thanks.
