### ISSUE TITLE
[Compatibility] 'multichannel' arg of sk-images in corruptions.py

### ISSUE THREAD

**Issue by Li-Qingyun** [hehaodong530/DOTA-C#3]
```
File "ImageNet-C/imagenet_c/imagenet_c/corruptions.py", line 178, in glass_blur
    x = np.uint8(gaussian(np.array(x) / 255., sigma=c[0], multichannel=True) * 255)
TypeError: gaussian() got an unexpected keyword argument 'multichannel'
```

It seems that scikit-image modify the interface of this func. There is description in the docstring of gaussian():

> Automatic detection of the color channel based on the old deprecated `multichannel=None` was broken in version 0.19. In 0.20 this
behavior is fixed. The last axis of an `image` with dimensions (M, N, 3) is interpreted as a color channel if `channel_axis` is not
set by the user (signaled by the default proxy value `ChannelAxisNotSet`). Starting with 0.22, `channel_axis=None` will be used as the new default value.

It's better to fix this to make sure the compatibility of this novel research.

**Comment by hehaodong530** [comment]
Hi @Li-Qingyun, thanks for your advice. To make the function compatible with the newer version of `skimage.filters.gaussian`, we replace the line
```
gaussian(..., ..., multichannel=True)
```
With the following:
```
gaussian(..., ..., channel_axis=2)
```

**Comment by Li-Qingyun** [comment]
Okkk, thanks for your quick reply!
